### ISSUE TITLE
data_generator代码在哪？

### ISSUE THREAD

**Issue by nuanyang123** [Tianxiaomo/Cultural_Inheritance-Recognizing_Chinese_Calligraphy_in_Multiple_Scenarios#2]
你好，请问dataset.py里面 from data_generator.generator import gen_data 这个data_generator代码在哪，可以提供一下吗？

**Comment by Tianxiaomo** [comment]
之前图片是自己生成的，后来发现和题目数据差别较大，识别率不高，且不让使用外部数据，所以最后使用的是题目给的训练数据，

**Comment by Tianxiaomo** [comment]
之前图片是自己生成的，后来发现和题目数据差别较大，识别率不高，且不让使用外部数据，所以最后使用的是题目给的训练数据，
