### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Icecream-blue-sky** [Tianxiaomo/Cultural_Inheritance-Recognizing_Chinese_Calligraphy_in_Multiple_Scenarios#5]
你好，我本来也想参加这个比赛，但知道的太晚了，不能报名了，请问里面你github提供的数据集是完整的吗？因为不能报名所以无法获得数据集，如果不是完整数据集，烦请将数据集发到我邮箱xxxxxx,不胜感激！！！

**Comment by Brave731** [comment]
可以发个百度网盘吗

**Comment by iou2much** [comment]
同求～

**Comment by VincentKan** [comment]
您好，确实需要数据集来辅助进一步研究，可否请您发到我的邮箱一份呢？不胜感激！
snow.kkk@163.com

**Comment by wyc2015fq** [comment]
您好，能发份数据吗？现在下载不了。感谢！！2140902076@cnu.edu.cn

**Comment by Aristotle-li** [comment]
您好，目前对这个十分感兴趣，可是现在下载不了了，能发一份嘛，感谢！！
1326150359@qq.com

**Comment by Icecream-blue-sky** [comment]
我也没有获得数据集，不要来问我了
